"""Avro schema definition for job listings."""

JOB_LISTING_SCHEMA = {
    "type": "record",
    "name": "JobListing",
    "namespace": "com.dataengineering.jobs",
    "doc": "Schema for job listing data",
    "fields": [
        {"name": "job_id", "type": "string", "doc": "Unique job identifier"},
        {"name": "site", "type": ["null", "string"], "default": None, "doc": "Job board site name"},
        {"name": "job_url", "type": ["null", "string"], "default": None, "doc": "URL to job posting"},
        {"name": "job_url_direct", "type": ["null", "string"], "default": None, "doc": "Direct application URL"},
        {"name": "title", "type": ["null", "string"], "default": None, "doc": "Job title"},
        {"name": "company", "type": ["null", "string"], "default": None, "doc": "Company name"},
        {"name": "location", "type": ["null", "string"], "default": None, "doc": "Job location"},
        {"name": "job_type", "type": ["null", "string"], "default": None, "doc": "Employment type"},
        {"name": "date_posted", "type": ["null", "string"], "default": None, "doc": "Date job was posted"},
        {"name": "interval", "type": ["null", "string"], "default": None, "doc": "Salary interval"},
        {"name": "min_amount", "type": ["null", "double"], "default": None, "doc": "Minimum salary"},
        {"name": "max_amount", "type": ["null", "double"], "default": None, "doc": "Maximum salary"},
        {"name": "currency", "type": ["null", "string"], "default": None, "doc": "Salary currency"},
        {"name": "is_remote", "type": ["null", "boolean"], "default": None, "doc": "Remote work flag"},
        {"name": "job_level", "type": ["null", "string"], "default": None, "doc": "Seniority level"},
        {"name": "job_function", "type": ["null", "string"], "default": None, "doc": "Job function category"},
        {"name": "listing_type", "type": ["null", "string"], "default": None, "doc": "Type of listing"},
        {"name": "emails", "type": ["null", "string"], "default": None, "doc": "Contact emails"},
        {"name": "description", "type": ["null", "string"], "default": None, "doc": "Job description"},
        {"name": "company_industry", "type": ["null", "string"], "default": None, "doc": "Company industry"},
        {"name": "company_url", "type": ["null", "string"], "default": None, "doc": "Company website"},
        {"name": "company_url_direct", "type": ["null", "string"], "default": None, "doc": "Direct company URL"},
        {"name": "company_addresses", "type": ["null", "string"], "default": None, "doc": "Company addresses"},
        {"name": "company_num_employees", "type": ["null", "int"], "default": None, "doc": "Number of employees"},
        {"name": "company_revenue", "type": ["null", "string"], "default": None, "doc": "Company revenue"},
        {"name": "company_description", "type": ["null", "string"], "default": None, "doc": "Company description"},
        {"name": "logo_photo_url", "type": ["null", "string"], "default": None, "doc": "Company logo URL"},
        {"name": "banner_photo_url", "type": ["null", "string"], "default": None, "doc": "Company banner URL"},
        {"name": "ceo_name", "type": ["null", "string"], "default": None, "doc": "CEO name"},
        {"name": "ceo_photo_url", "type": ["null", "string"], "default": None, "doc": "CEO photo URL"},
        {"name": "search_term", "type": "string", "doc": "Search term used to find this job"},
        {
            "name": "ingestion_timestamp",
            "type": "long",
            "logicalType": "timestamp-millis",
            "doc": "Ingestion timestamp",
        },
        {"name": "ingestion_date", "type": "string", "doc": "Date partition key (YYYY-MM-DD)"},
        {"name": "pipeline_version", "type": "string", "default": "1.0.0", "doc": "Pipeline version"},
    ],
}
