name: "rats_dbt_transformer"
version: "1.0.0"
config-version: 2

profile: "rats_dbt_transformer"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

flags:
  use_managed_iceberg: true
  use_materialization_v2: true

models:
  rats_dbt_transformer:
    staging:
      +materialized: view
    intermediate:
      +materialized: ephemeral
    marts:
      +tags: ["mart"]
      +materialized: incremental
